#!/bin/bash
#
# Build an installable .lbplugin (zip) archive of this plugin.
# Output: <plugin>-<version>-snapshot.zip in the repo root.
#
# The archive contains a snapshot of the current working tree — uncommitted
# changes included. Use this for hand-testing on the LoxBerry; cut a proper
# git tag + release.cfg bump for AUTOUPDATE users.

set -euo pipefail

# Read plugin metadata from plugin.cfg.
PLUGIN_NAME="$(grep -E '^FOLDER=' plugin.cfg | head -1 | cut -d'=' -f2-)"
[ -z "$PLUGIN_NAME" ] && PLUGIN_NAME="alexa-aloxberry"
VERSION="$(grep -E '^VERSION=' plugin.cfg | head -1 | cut -d'=' -f2-)"
[ -z "$VERSION" ] && VERSION="dev"
VERSION="${VERSION}-snapshot"

if ! command -v zip >/dev/null 2>&1; then
    echo "ERROR: zip is required. Install: apt install zip  (or: choco install zip on Windows)" >&2
    exit 1
fi

ARCHIVE_NAME="${PLUGIN_NAME}-${VERSION}.zip"

echo "Building $ARCHIVE_NAME ..."
echo ""

# Stage everything into a tempdir under a directory named after the plugin —
# LoxBerry expects the zip root to contain a single folder with the plugin
# files, not the files directly.
TEMP_DIR="$(mktemp -d)"
STAGE_DIR="$TEMP_DIR/$PLUGIN_NAME"
mkdir -p "$STAGE_DIR"
trap 'rm -rf "$TEMP_DIR"' EXIT

# What goes INTO the plugin ZIP: only the plugin-payload subset of the repo.
# aws/ and bridge/ are separate deploy artifacts (Lambda + bridge container);
# they are NEVER part of the LoxBerry plugin.
#
# rsync filter rules: first match wins. We list INCLUDES first, then catch-all
# EXCLUDES that drop everything else. Trailing `/` matches dirs only.
RSYNC_RULES=(
    # Top-level plugin metadata
    --include='plugin.cfg'
    --include='release.cfg'
    --include='prerelease.cfg'
    --include='preinstall.sh'
    --include='postinstall.sh'
    --include='preupgrade.sh'
    --include='postupgrade.sh'

    # Uninstall hook (lives in a directory by LoxBerry convention)
    --include='uninstall/'
    --include='uninstall/**'

    # cron/ — auto-start at boot
    --include='cron/'
    --include='cron/cron.reboot'
    --include='cron/crontab'

    # icons/, templates/, doc/ — UI assets (may not exist yet; fine)
    --include='icons/'
    --include='icons/**'
    --include='templates/'
    --include='templates/**'
    --include='doc/'
    --include='doc/**'

    # webfrontend/ — CGI files (config UI under htmlauth/plugins/<plugin>/).
    # The .gitkeep that used to live alone in htmlauth/ tripped LoxBerry's
    # installer (it strips dotfiles, then `cp htmlauth/*` matches no files).
    # Now that there's an index.cgi the directory is non-empty and ships.
    --include='webfrontend/'
    --include='webfrontend/**'

    # bin/ — the daemon and its helpers.
    # We include the *runtime* surface and explicitly drop dev-only subdirs.
    --include='bin/'
    --exclude='bin/node_modules/'         # regenerated by postinstall.sh
    --exclude='bin/scripts/'              # workstation dev/tail tools
    --exclude='bin/test/'                 # unit tests
    --exclude='bin/data/'                 # local-dev state
    --include='bin/src/'
    --include='bin/src/**'
    --include='bin/control.sh'
    --include='bin/tail-daemon.sh'
    --include='bin/log-session-create.pl'
    --include='bin/lox-getconfig.pl'
    --include='bin/lox-getstructure.pl'
    --include='bin/lox-send.pl'
    --include='bin/lox-control.pl'
    --include='bin/package.json'
    --include='bin/package-lock.json'
    --include='bin/.gitkeep'

    # Final catch-all: drop everything that didn't match above.
    --exclude='*'
)

if command -v rsync >/dev/null 2>&1; then
    rsync -a "${RSYNC_RULES[@]}" ./ "$STAGE_DIR/"
else
    echo "rsync is not installed; cannot reliably stage the plugin tree." >&2
    echo "Install with: apt install rsync   (or: choco install rsync)" >&2
    exit 1
fi

# Permissions: lifecycle hooks, control.sh, tail-daemon.sh, cron.reboot,
# .pl helpers, and the uninstall hook must all be executable inside the zip.
find "$STAGE_DIR" -maxdepth 1 -type f -name '*.sh'    -exec chmod +x {} \;
find "$STAGE_DIR/cron"     -type f -name 'cron.*'      -exec chmod +x {} \; 2>/dev/null || true
find "$STAGE_DIR/uninstall" -type f                    -exec chmod +x {} \; 2>/dev/null || true
chmod +x "$STAGE_DIR/bin/control.sh"            2>/dev/null || true
chmod +x "$STAGE_DIR/bin/tail-daemon.sh"        2>/dev/null || true
chmod +x "$STAGE_DIR/bin/log-session-create.pl" 2>/dev/null || true
chmod +x "$STAGE_DIR/bin/lox-getconfig.pl"      2>/dev/null || true
chmod +x "$STAGE_DIR/bin/lox-send.pl"           2>/dev/null || true

# Quick sanity check before we zip.
for required in plugin.cfg preinstall.sh postinstall.sh bin/src/index.js bin/package.json bin/control.sh cron/cron.reboot; do
    if [ ! -e "$STAGE_DIR/$required" ]; then
        echo "ERROR: staged tree is missing $required — refusing to package." >&2
        exit 1
    fi
done

# Show what we're shipping (compact).
echo "Staged tree:"
( cd "$STAGE_DIR" && find . -type f | sed 's|^\./|  |' | sort )

# Build the zip.
(
    cd "$TEMP_DIR"
    zip -rq "$ARCHIVE_NAME" "$PLUGIN_NAME"
    mv "$ARCHIVE_NAME" "$OLDPWD/"
)

SIZE="$(du -h "$ARCHIVE_NAME" | cut -f1)"
echo ""
echo "✓ Built $ARCHIVE_NAME  ($SIZE)"
echo "  Upload via: LoxBerry → Plugin install → choose this file"
