#!/usr/bin/env bash
#
# Full production deploy for the Aloxberry AWS backend.
#
# Sibling of deploy-prod.ps1 — same behaviour, bash flavour. Use whichever
# one matches your shell; the only practical difference is PowerShell uses
# .NET's RandomNumberGenerator while this one shells out to `openssl rand`.
#
# What it does, in order:
#   1. Verifies AWS CLI is logged in to the expected profile/region.
#   2. Ensures both SSM SecureString secrets exist:
#        /loxberry-alexa/jwt-secret              (Lambda → user-facing JWT signing)
#        /loxberry-alexa/bridge-dispatch-secret  (Lambda ↔ bridge shared secret)
#      If a secret is missing, generates 32 random bytes and writes it.
#   3. Clears stale @aloxberry/shared snapshots + .aws-sam cache (npm's file:
#      deps don't refresh on content-only edits).
#   4. Runs `sam build --build-in-source`.
#   5. Runs `sam deploy` against the samconfig.toml in aws/ — which already
#      includes BridgeUrl + BridgeDispatchSecretParam in parameter_overrides.
#   6. Prints the stack outputs.
#
# After the SSM secrets are created, the bridge container needs the SAME value
# as /loxberry-alexa/bridge-dispatch-secret in its BRIDGE_DISPATCH_SECRET env
# var. The script prints the value so you can paste it into bridge/.env. If
# the secret already existed, you can re-print it with --show-bridge-secret.
#
# Usage:
#   ./aws/scripts/deploy-prod.sh
#   ./aws/scripts/deploy-prod.sh --build-only
#   ./aws/scripts/deploy-prod.sh --show-bridge-secret   # just dump the value, no deploy
#   ./aws/scripts/deploy-prod.sh --profile X --region eu-west-1
#   ./aws/scripts/deploy-prod.sh --log-level DEBUG      # verbose Lambda logging

set -euo pipefail

PROFILE='loxberry-alexa'
REGION='eu-west-1'
BUILD_ONLY=0
SHOW_BRIDGE_SECRET=0
# Default INFO. Lambda's @aloxberry/shared logger filters anything below this
# level — CloudWatch ingestion volume scales with how many per-request lines
# survive. DEBUG fires everything (use for investigation); INFO keeps only
# lifecycle events + warnings + errors (production default).
LOG_LEVEL='INFO'

while [[ $# -gt 0 ]]; do
    case "$1" in
        --build-only)         BUILD_ONLY=1; shift ;;
        --show-bridge-secret) SHOW_BRIDGE_SECRET=1; shift ;;
        --profile)            PROFILE="$2"; shift 2 ;;
        --region)             REGION="$2";  shift 2 ;;
        --log-level)          LOG_LEVEL="$2"; shift 2 ;;
        -h|--help)
            sed -n '2,32p' "$0"
            exit 0
            ;;
        *) echo "Unknown option: $1" >&2; exit 2 ;;
    esac
done

# Validate LOG_LEVEL against the template's AllowedValues — fail fast with a
# useful message rather than letting CloudFormation reject the deploy.
case "$LOG_LEVEL" in
    DEBUG|INFO|WARN|ERROR) ;;
    *) echo "Invalid --log-level '$LOG_LEVEL'. Must be DEBUG, INFO, WARN, or ERROR." >&2
       exit 2 ;;
esac

JWT_PARAM='/loxberry-alexa/jwt-secret'
BRIDGE_PARAM='/loxberry-alexa/bridge-dispatch-secret'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AWS_DIR="$(dirname "${SCRIPT_DIR}")"
TEMPLATE="${AWS_DIR}/infrastructure/template.yaml"

# ---------- helpers ---------------------------------------------------------

ssm_param_exists() {
    aws ssm get-parameter \
        --name "$1" --region "$REGION" --profile "$PROFILE" \
        --with-decryption >/dev/null 2>&1
}

ssm_param_get() {
    aws ssm get-parameter \
        --name "$1" --region "$REGION" --profile "$PROFILE" \
        --with-decryption --query 'Parameter.Value' --output text
}

# Value is generated by the caller and passed in. Capturing it via
# $(func) would defeat `set -e` because variable assignment from command
# substitution doesn't propagate the inner exit status.
ssm_secret_create() {
    local name="$1" description="$2" value="$3"
    echo "  Creating SecureString $name ..." >&2
    aws ssm put-parameter \
        --name "$name" \
        --type SecureString \
        --value "$value" \
        --description "$description" \
        --region "$REGION" \
        --profile "$PROFILE" \
        --tags 'Key=project,Value=loxberry-alexa' >/dev/null
}

# ---------- --show-bridge-secret shortcut ----------------------------------

if [[ "$SHOW_BRIDGE_SECRET" -eq 1 ]]; then
    if ! ssm_param_exists "$BRIDGE_PARAM"; then
        echo "Bridge dispatch secret has not been created yet. Run without --show-bridge-secret first." >&2
        exit 1
    fi
    val="$(ssm_param_get "$BRIDGE_PARAM")"
    echo
    echo "BRIDGE_DISPATCH_SECRET=$val"
    echo "(put this into bridge/.env on the host running the bridge)"
    exit 0
fi

# ---------- preflight -------------------------------------------------------

if [[ ! -f "$TEMPLATE" ]]; then
    echo "SAM template not found at $TEMPLATE" >&2
    exit 1
fi

echo "==> Preflight: aws sts get-caller-identity --profile $PROFILE"
if ! aws sts get-caller-identity --profile "$PROFILE" --region "$REGION" >/dev/null; then
    echo "AWS profile '$PROFILE' is not configured or has expired credentials." >&2
    exit 1
fi

# ---------- SSM secrets -----------------------------------------------------

echo "==> Ensuring SSM SecureString secrets exist"

BRIDGE_JUST_CREATED=0
BRIDGE_VALUE=''

if ssm_param_exists "$JWT_PARAM"; then
    echo "  [ok] $JWT_PARAM already exists"
else
    ssm_secret_create "$JWT_PARAM" \
        'JWT signing secret for Aloxberry OAuth access tokens' \
        "$(openssl rand -hex 32)"
    echo "  [ok] $JWT_PARAM created"
fi

if ssm_param_exists "$BRIDGE_PARAM"; then
    echo "  [ok] $BRIDGE_PARAM already exists"
else
    BRIDGE_VALUE="$(openssl rand -hex 32)"
    ssm_secret_create "$BRIDGE_PARAM" \
        'Shared secret authenticating Lambda calls to the bridge /dispatch endpoint' \
        "$BRIDGE_VALUE"
    BRIDGE_JUST_CREATED=1
    echo "  [ok] $BRIDGE_PARAM created"
fi

# ---------- build + deploy --------------------------------------------------

cd "$AWS_DIR"

echo "==> Clearing stale @aloxberry/shared snapshots + .aws-sam cache"
for handler in alexa-handler oauth-handler; do
    stale="$AWS_DIR/lambda/$handler/node_modules/@aloxberry"
    if [[ -d "$stale" ]]; then
        echo "  removing $stale"
        rm -rf "$stale"
    fi
done
sam_build_cache="$AWS_DIR/.aws-sam"
if [[ -d "$sam_build_cache" ]]; then
    echo "  removing $sam_build_cache"
    rm -rf "$sam_build_cache"
fi

echo
echo "==> sam build --build-in-source"
sam build --template-file "$TEMPLATE" --build-in-source

if [[ "$BUILD_ONLY" -eq 1 ]]; then
    echo "Build complete (no deploy)."
    exit 0
fi

echo
echo "==> sam deploy (LogLevel=$LOG_LEVEL)"
echo "    (BridgeUrl + BridgeDispatchSecretParam come from samconfig.toml)"
# --parameter-overrides MERGES with samconfig.toml's parameter_overrides
# (it doesn't replace), so BridgeUrl etc. remain in effect. Only LogLevel
# is overridden here.
sam deploy --profile "$PROFILE" --region "$REGION" \
    --parameter-overrides "LogLevel=$LOG_LEVEL"

echo
echo "==> Stack outputs"
aws cloudformation describe-stacks \
    --stack-name 'loxberry-alexa' \
    --profile "$PROFILE" --region "$REGION" \
    --query 'Stacks[0].Outputs' \
    --output table

# ---------- footer ----------------------------------------------------------

if [[ "$BRIDGE_JUST_CREATED" -eq 1 ]]; then
    echo
    echo "============================================================"
    echo " Bridge dispatch secret was just created."
    echo " Put the value below into bridge/.env on the bridge host:"
    echo
    echo " BRIDGE_DISPATCH_SECRET=$BRIDGE_VALUE"
    echo
    echo " You can re-print this later with:"
    echo "   ./aws/scripts/deploy-prod.sh --show-bridge-secret"
    echo "============================================================"
fi

echo
echo "Deploy complete."
